<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

	  <TargetFramework>net8.0</TargetFramework>


  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.2.5" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="AutoMapper" Version="13.0.1" />

    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contracts\Contracts.csproj" />
    <ProjectReference Include="..\Sample.Product.Domain\Sample.Product.Domain.csproj" />
  </ItemGroup>

</Project>
