<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MySvc.Framework.Infrastructure.Job.Hangfire</AssemblyName>
    <RootNamespace>MySvc.Framework.Infrastructure.Job.Hangfire</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.Core" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Infrastructure.Crosscutting\Infrastructure.Crosscutting.csproj" />
  </ItemGroup>
</Project>