<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0</TargetFramework>


	  <RootNamespace>MySvc.Framework.Infrastructure.Serilog</RootNamespace>
    <AssemblyName>MySvc.Framework.Infrastructure.Serilog</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="3.1.1" />
    <PackageReference Include="Serilog.Sinks.PeriodicBatching" Version="4.0.0" />
    <PackageReference Include="MailKit" Version="4.4.0" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>

</Project>
