<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>MySvc.Framework.Infrastructure.Serilog</RootNamespace>
    <AssemblyName>MySvc.Framework.Infrastructure.Logging.Serilog</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.PeriodicBatching" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="System.Text.RegularExpressions" />
  </ItemGroup>
</Project>