//=======================================================================================
//
// Copyright (C) 2010-2011 Asia-Peak Technologies, Inc. All Rights Reserved.
// 
// All the code, text, graphics, media, design, programs and other works are
// protected by copyright law. Unauthorized reproduction or redistribution of them,  
// or any portion of them, are forbidden.
// 
//=======================================================================================
//---------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------

namespace MySvc.DotNetCore.Framework.Infrastructure.Authorization.Client.Extensions
{	
	public static class Error
    {
		public static class Names
		{
				/// <summary>
				/// Token过期，请重新登录
				/// </summary>
				public const string TokenExpired = "Token过期，请重新登录";

				/// <summary>
				/// 获取权限失败
				/// </summary>
				public const string RequestPermissionFailed = "获取权限失败";

				/// <summary>
				/// 获取用户信息失败
				/// </summary>
				public const string RequestUserProfileFailed = "获取用户信息失败";

					}

		public static class Codes
		{
			/// <summary>
			/// token-expired
			/// </summary>
			public const string TokenExpired = "token-expired";

			/// <summary>
			/// request-permission-failed
			/// </summary>
			public const string RequestPermissionFailed = "request-permission-failed";

			/// <summary>
			/// request-userProfile-failed
			/// </summary>
			public const string RequestUserProfileFailed = "request-userProfile-failed";

				}

    }
}