<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>MySvc.Framework.Infrastructure.AutoMapper</AssemblyName>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>8.0.0-beta4</Version>
    <RootNamespace>MySvc.Framework.Infrastructure.AutoMapper</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Infrastructure.Crosscutting\Infrastructure.Crosscutting.csproj" />
  </ItemGroup>
</Project>