<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>MySvc.Framework.Applications.Common</AssemblyName>
    <RootNamespace>MySvc.Framework.Applications.Common</RootNamespace>
    <Version>8.0.0-beta4</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>bin\Release\net8.0\MySvc.Framework.Applications.Common.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>bin\Debug\net8.0\MySvc.Framework.Applications.Common.xml</DocumentationFile>
  </PropertyGroup>

</Project>
