<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Moq.Contrib.HttpClient" />

  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Infrastructure.Authorization.Client\Infrastructure.Authorization.Client.csproj" />
  </ItemGroup>
</Project>