<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>

	  <TargetFramework>net8.0</TargetFramework>

	  <DockerComposeProjectPath>..\..\docker-compose.dcproj</DockerComposeProjectPath>
    <UserSecretsId>42811497-7821-49c9-b654-b7ef751e50ec</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Applications\IntegrationEvents\EventHandling\" />
    <Folder Include="IntegrationEvents\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />

	  <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="MassTransit" Version="8.2.5" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.8.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Domain.Core\Domain.Core.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure.Crosscutting.Json.NewtonsoftJson\Infrastructure.Crosscutting.Json.NewtonsoftJson.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure.Crosscutting\Infrastructure.Crosscutting.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure.Data.MongoDB\Infrastructure.Data.MongoDB.csproj" />
    <ProjectReference Include="..\Catalog.Domain\Catalog.Domain.csproj" />
    <ProjectReference Include="..\CataLog.Infrastructure.MongoDB.Repository\CataLog.Infrastructure.MongoDB.Repository.csproj" />
  </ItemGroup>

</Project>
