//=======================================================================================
//
// Copyright (C) 2010-2011 Asia-Peak Technologies, Inc. All Rights Reserved.
// 
// All the code, text, graphics, media, design, programs and other works are
// protected by copyright law. Unauthorized reproduction or redistribution of them, 
// or any portion of them, are forbidden.
// 
//=======================================================================================
//---------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------

using System;

namespace MySvc.DotNetCore.Framework.IS4.Domain.Exceptions
{    

        public static class Error
    {
		public static class Names
		{
				/// <summary>
				/// 密码错误
				/// </summary>
				public const string PasswordMismatch = "密码错误";

					}

		public static class Codes
		{
			/// <summary>
			/// password-mismatch
			/// </summary>
			public const string PasswordMismatch = "password-mismatch";

				}

    }
    
}