<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>MySvc.Framework.IS4.MongoDB</AssemblyName>
    <RootNamespace>MySvc.Framework.IS4.MongoDB</RootNamespace>
    <!-- 抑制IdentityServer4安全漏洞警告 -->
    <NoWarn>$(NoWarn);NU1902</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="IdentityServer4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Infrastructure.Crosscutting\Infrastructure.Crosscutting.csproj" />
    <ProjectReference Include="..\Infrastructure.Data.MongoDB\Infrastructure.Data.MongoDB.csproj" />
    <ProjectReference Include="..\IS4.Domain\IS4.Domain.csproj" />
  </ItemGroup>
</Project>