<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>MySvc.Framework.Infrastructure.NewtonsoftJson</RootNamespace>
    <AssemblyName>MySvc.Framework.Infrastructure.Crosscutting.Json.NewtonsoftJson</AssemblyName>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Infrastructure.Crosscutting\Infrastructure.Crosscutting.csproj" />
  </ItemGroup>
</Project>